baseurl = "/"
title = "David Goldstein"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = '

    <a href="mailto:DGoldstein01@gmail.com" id="mail-main">
      <button>
        <i class="fa fa-envelope"></i>      
      </button>
    </a>

    <a href="https://github.com/dgoldstein1" id="github-main">
      <button>
        <i class="fa fa-github"></i>
      </button>
    </a>

    <a href="https://www.linkedin.com/in/david-goldstein-1211388a" id="linkedin-main">
      <button>
        <i class="fa fa-linkedin"></i>      
      </button>
    </a>    

    <a href="/documents/David Goldstein Resume.pdf" id="resume-main" download>
      <button class="fa fa-download">
        Resume
      </button>
    </a>


<script>
  // remove underline for <a> elements on this page
  document.getElementById("mail-main").style.border = "none"
  document.getElementById("github-main").style.border = "none"
  document.getElementById("linkedin-main").style.border = "none"
  document.getElementById("resume-main").style.border = "none"

</script


  '
  logo = ""
  copyright = "David Goldstein 2017"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "fa-envelope"

[languages]
[languages.en]
languageName = "English"
weight = 1



















