baseurl = "/"
title = "David Goldstein"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = '

    <a href="mailto:DGoldstein01@gmail.com" id="mail-main">
      <button>
        <i class="fa fa-envelope"></i>      
      </button>
    </a>

    <a href="https://github.com/dgoldstein1" id="github-main">
      <button>
        <i class="fa fa-github"></i>
      </button>
    </a>

    <a href="https://www.linkedin.com/in/david-goldstein-1211388a" id="linkedin-main">
      <button>
        <i class="fa fa-linkedin"></i>      
      </button>
    </a>    

    <a href="/documents/David Goldstein Resume.pdf" id="resume-main" download>
      <button class="fa fa-download">
        Resume
      </button>
    </a>


<script>
  document.getElementById("mail-main").style.border = "none";
    document.getElementById("github-main").style.border = "none";
    document.getElementById("linkedin-main").style.border = "none";
    document.getElementById("resume-main").style.border = "none";

    // send out requests
    let geoIpServer="/api/geoIpServer?access_key=7eca814a6de384aab338e110c57fef37"
    let metricsServer="/api/websiteAnalytics"
    let localinstance="http://localhost:5000/visits"

    // get IP information and send to analytics database
    $.getJSON(geoIpServer, function(ipResponse){
      console.log("current ip Response", ipResponse)
      if (ipResponse) {
        // add in href
        ipResponse.href = window.location.search.substr(1)
        // formulate request to metrics server
        $.post(metricsServer, JSON.stringify(ipResponse), function(res) {
          console.log("response from db",res)
        })
      }
    });

</script



  '
  logo = ""
  copyright = "David Goldstein 2017"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "fa-envelope"

[languages]
[languages.en]
languageName = "English"
weight = 1



















