baseurl = "http://example.org"
title = "David Goldstein"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = "DGoldstein01@gmail.com"
  logo = ""
  copyright = "David Goldstein 2017"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "fa-envelope"

[languages]
[languages.en]
languageName = "English"
weight = 1



















