[[redirects]]
  from = "/api/geoIpServer"
  to = "http://api.ipstack.com/check"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  query={access_key = ":access_key"}
  # headers = {X-From = "Netlify"} # COMMENT: add this header to the search request
  # signed = "API_SIGNATURE_TOKEN" # COMMENT: sign each request with the value of this env variable

[[redirects]]
  from = "/api/websiteAnalytics/*"
  to = "https://quiet-brushlands-26130.herokuapp.com/visits"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  # headers = {X-From = "Netlify"} # COMMENT: add this header to the search request
  # signed = "API_SIGNATURE_TOKEN" # COMMENT: sign each request with the value of this env variable  
